### PR TITLE
Feature/substraction

### PR DESCRIPTION
**Pull request by dmartmont**

### CODE REVIEW

**Comment by dmarttest** [comment]
Can one of the admins verify this patch?

**Comment by dmarttest** [comment]
Can one of the admins verify this patch?

**Comment by dmarttest** [comment]
Can one of the admins verify this patch?

**Comment by dmartmont** [comment]
Run tests

**Comment by dmarttest** [comment]
Run tests

**Comment by dmarttest** [comment]
Can one of the admins verify this patch?

**Pull request closed without merging**
